Repository aeternity/aepp-sdk-js, pull requests merged in 2019-12, with the labels that each got.

#809 feat(CI): Move to Travis CI
  .travis.yml
  Jenkinsfile
  README.md
  docker-compose.yml
  es/ae/contract.js
  package.json
  test/integration/channel.js
  test/integration/contract.js
  test/integration/index.js
Labels: feature

#820 feat(ci): enable daily builds on latest node and compiler and enable codecov
  .env
  .gitignore
  .travis.yml
  Dockerfile.ci
  docker-compose.yml
  package-lock.json
  package.json
  pnpm-lock.yaml
  test/integration/index.js
Labels: review

#828 fix(Contract/Chain): Using { waitMined: false } with Contract high lvl API
  es/ae/contract.js
  es/contract/aci/index.js
  test/integration/contract.js
Labels: bug

#830 feat(Test): Increase code covarage
  es/chain/node.js
  es/contract/compiler.js
  test/integration/chain.js
  test/integration/contract.js
  test/integration/index.js
  test/integration/node.js
  test/integration/transaction.js
  test/unit/swagger.js
  test/unit/tx.js
Labels: enhancement

#829 refactor(Cross-Node): Remove cross-node compatibility code
  es/ae/aens.js
  es/ae/universal.js
  es/chain/index.js
  es/chain/node.js
  es/contract/compiler.js
  es/contract/ga/helpers.js
  es/node.js
  es/tx/builder/helpers.js
  es/tx/tx.js
  test/integration/aens.js
Labels: enhancement

#697 refactor(AE): Remove all deprecated stuff
  README.md
  docs/examples/node/aewallet.md
  docs/guides/import-nodejs.md
  docs/guides/import-script-tag.md
  docs/guides/low-vs-high-usage.md
  es/account/memory.js
  es/accounts.js
  es/ae/contract.js
  es/ae/oracle.js
  es/contract/aci/index.js
  es/contract/ga/helpers.js
  es/node-pool/index.js
  es/tx/builder/schema.js
  es/tx/tx.js
  es/utils/keystore.js
  examples/README.md
  examples/node/aecontract.js
  examples/node/aewallet.js
  package.json
  test/integration/accounts.js
  test/integration/aens.js
  test/integration/channel.js
  test/integration/index.js
  test/integration/transaction.js
  test/integration/txVerification.js
Labels: enhancement

#815 feat(Wallet): Use `postMessage` for communication with extension wall…
  docs/api.md
  docs/api/accounts.md
  docs/api/ae.md
  docs/api/ae/aepp.md
  docs/api/ae/contract.md
  docs/api/ae/wallet.md
  docs/api/contract/aci.md
  docs/api/utils/aepp-wallet-communication/connection.md
  docs/api/utils/aepp-wallet-communication/connection/browser-runtime.md
  docs/api/utils/aepp-wallet-communication/connection/browser-window-message.md
  docs/api/utils/aepp-wallet-communication/content-script-bridge.md
  docs/api/utils/aepp-wallet-communication/rpc/aepp-rpc.md
  docs/api/utils/aepp-wallet-communication/rpc/rpc-client.md
  docs/api/utils/aepp-wallet-communication/rpc/wallet-rpc.md
  docs/api/utils/aepp-wallet-communication/wallet-detector.md
  docs/guides/how-to-build-aepp-using-new-wallet-api.md
  docs/guides/how-to-build-an-wallet-app-or-extension.md
  es/ae/contract.js
  es/ae/index.js
  es/utils/aepp-wallet-communication/connection/browser-runtime.js
  es/utils/aepp-wallet-communication/connection/browser-window-message.js
  es/utils/aepp-wallet-communication/connection/index.js
  es/utils/aepp-wallet-communication/content-script-bridge.js
  es/utils/aepp-wallet-communication/helpers.js
  es/utils/aepp-wallet-communication/rpc/aepp-rpc.js
  es/utils/aepp-wallet-communication/rpc/rpc-clients.js
  es/utils/aepp-wallet-communication/rpc/wallet-clients.js
  es/utils/aepp-wallet-communication/rpc/wallet-rpc.js
  es/utils/aepp-wallet-communication/schema.js
  es/utils/aepp-wallet-communication/wallet-connection/browser-runtime.js
  es/utils/aepp-wallet-communication/wallet-connection/browser-window-message.js
  es/utils/aepp-wallet-communication/wallet-detector.js
  examples/browser/extension/package-lock.json
  examples/browser/extension/package.json
  examples/browser/extension/src/js/background.js
  examples/browser/extension/src/js/inject.js
  examples/browser/vuejs/connect-two-ae/aepp/package.json
  examples/browser/vuejs/connect-two-ae/aepp/src/components/Home.vue
  examples/browser/vuejs/connect-two-ae/identity/package.json
  examples/browser/vuejs/connect-two-ae/identity/src/components/Home.vue
Labels: feature, in progress, review

#834 test(Aepp<->Wallet): Add tests for Aepp<->Wallet comunication
  es/ae/wallet.js
  es/tx/builder/helpers.js
  es/utils/aepp-wallet-communication/rpc/aepp-rpc.js
  es/utils/aepp-wallet-communication/rpc/rpc-clients.js
  es/utils/aepp-wallet-communication/rpc/wallet-rpc.js
  es/utils/aepp-wallet-communication/schema.js
  es/utils/crypto.js
  test/integration/aens.js
  test/integration/index.js
  test/integration/rpc.js
Labels: feature
