Repository aeternity/aepp-sdk-js, pull requests merged in 2019-08, with the labels that each got.

#574 feat(NodePool): Implement NodePool stamp
  es/account/index.js
  es/chain/index.js
  es/chain/node.js
  es/node-pool/helpers.js
  es/node-pool/index.js
  es/node.js
  es/oracle/index.js
  es/oracle/node.js
  es/tx/builder/index.js
  es/tx/tx.js
  es/tx/validator.js
  examples/browser/vuejs/connect-two-ae/identity/src/components/Home.vue
  test/integration/epoch.js
  test/integration/node.js
Labels: feature

#577 Dry run with 0 account
  es/account/selector.js
  es/ae/contract.js
  es/utils/crypto.js
Labels: feature

#579 feat(TxBuilder): Add helper for producing tx hash
  es/tx/builder/helpers.js
  es/tx/builder/index.js
  es/utils/crypto.js
  test/unit/crypto.js
Labels: feature

#591 Feat(AE): ability to use specific account for one operation
  es/account/selector.js
  es/accounts.js
  es/ae/aens.js
  es/ae/contract.js
  es/ae/index.js
  es/ae/oracle.js
  es/utils/json-big.js
  es/utils/swagger.js
  test/integration/accounts.js
  test/integration/aens.js
  test/integration/contract.js
  test/integration/index.js
  test/unit/swagger.js
Labels: feature

#594 feat(MemoryAccount): Add validation of keypair
  es/account/memory.js
  es/account/selector.js
  es/utils/crypto.js
  es/utils/keystore.js
  es/utils/string.js
  test/unit/memory-account.js
Labels: feature

#605 Keypair verification
  es/utils/crypto.js
  test/unit/crypto.js
Labels: bug

#607 fix(Swagger): Always throw error from `axios` error handler
  es/node.js
Labels: enhancement

#603 docs(Oracle): Fix arguments in jsdoc
  es/ae/oracle.js
Labels: enhancement

#449 feat(GA): Generalized account
  docs/api.md
  docs/api/ae/oracle.md
  docs/api/contract/ga.md
  docs/api/tx/builder.md
  es/account/memory.js
  es/ae/aepp.js
  es/ae/index.js
  es/ae/universal.js
  es/ae/wallet.js
  es/chain/index.js
  es/contract/ga/helpers.js
  es/contract/ga/index.js
  es/index.js
  es/tx/builder/index.js
  es/tx/builder/schema.js
  es/tx/index.js
  es/tx/tx.js
  es/tx/validator.js
  test/integration/ga.js
  test/unit/memory-account.js
Labels: feature, in progress
