Repository aeternity/aepp-sdk-js, pull requests merged in 2019-05, with the labels that each got.

#347 connect two ae examples: Refactor and add spend with payload
  examples/connect-two-ae/aepp/src/components/Home.vue
  examples/connect-two-ae/aepp/src/index.js
  examples/connect-two-ae/identity/src/components/Home.vue
  examples/connect-two-ae/identity/src/index.html
  examples/connect-two-ae/identity/src/index.js
Labels: review

#371 feat(AE): Allow to spend % of balance.
  es/ae/index.js
  test/integration/accounts.js
Labels: review

#348 Add prototype of reverse iframe approach to example aepp
  examples/connect-two-ae/aepp/src/components/Home.vue
  examples/connect-two-ae/identity/src/components/Home.vue
Labels: review

#384 feat(ACI): Implement arguments validation for generic sophia types(list, map, tuple, record)
  es/contract/aci.js
  package-lock.json
  package.json
  test/integration/contract.js
Labels: in progress

#368 Init config for argon2 in browser
  es/contract/aci.js
  es/utils/keystore.js
  examples/connect-two-ae/aepp/package-lock.json
  examples/connect-two-ae/aepp/package.json
  examples/connect-two-ae/aepp/src/components/Home.vue
  examples/connect-two-ae/aepp/webpack.config.js
  examples/connect-two-ae/identity/package-lock.json
  examples/connect-two-ae/identity/src/components/Home.vue
  examples/connect-two-ae/identity/webpack.config.js
  package-lock.json
  package.json
Labels: enhancement

#388 rpc client: Handle case if aepp opened without wallet
  es/rpc/client.js
Labels: enhancement

#390 feat(ACI): Add `Option` sophia type to ACI
  es/contract/aci.js
  test/integration/contract.js
Labels: feature

#396 fix(ACI): Add ability to pass zero address as number.
  .env
  es/contract/aci.js
  test/integration/contract.js
Labels: enhancement

#397 feat(Fortuna): Node 3.0.0 compatibility
  es/ae/contract.js
  es/ae/oracle.js
  es/chain/node.js
  es/node.js
  es/tx/builder/index.js
  es/tx/builder/schema.js
  es/tx/tx.js
  es/utils/semver-satisfies.js
  test/integration/contract.js
Labels: enhancement

#413 feat(Consensus): Add function to get consensus version.
  .env
  docker/aeternity_node_mean16.yaml
  es/node.js
  es/tx/builder/index.js
  es/tx/builder/schema.js
  es/tx/tx.js
  test/integration/accounts.js
  test/integration/channel.js
Labels: enhancement

#424 Feature/improve fee calculation
  es/tx/builder/index.js
  es/tx/builder/schema.js
Labels: enhancement

#425 Feature/add vm version validation to tx validator
  es/tx/builder/schema.js
  es/tx/validator.js
  test/integration/channel.js
  test/integration/txVerification.js
Labels: enhancement

#426 Feature/improve tx validation
  es/tx/builder/schema.js
  es/tx/validator.js
Labels: enhancement

#431 Feature/add ability to intercept error from axios
  es/node.js
  es/utils/swagger.js
Labels: enhancement

#437 Release/3.4.0
  .env
  CHANGELOG.md
  README.md
  docs/api/account.md
  docs/api/account/memory.md
  docs/api/account/selector.md
  docs/api/accounts.md
  docs/api/ae.md
  docs/api/ae/aens.md
  docs/api/ae/aepp.md
  docs/api/ae/contract.md
  docs/api/ae/oracle.md
  docs/api/ae/universal.md
  docs/api/ae/wallet.md
  docs/api/chain.md
  docs/api/chain/node.md
  docs/api/channel/index.md
  docs/api/contract.md
  docs/api/contract/aci.md
  docs/api/contract/compiler.md
  docs/api/node.md
  docs/api/oracle.md
  docs/api/oracle/node.md
  docs/api/rpc/client.md
  docs/api/tx.md
  docs/api/tx/builder.md
  docs/api/tx/builder/helpers.md
  docs/api/tx/builder/schema.md
  docs/api/tx/tx.md
  docs/api/tx/validator.md
  docs/api/utils/swagger.md
  es/channel/internal.js
  es/node.js
  es/tx/builder/index.js
  es/tx/builder/schema.js
  es/tx/validator.js
  es/utils/swagger.js
  package.json
  test/integration/txVerification.js
Labels: enhancement

#439 feat(ACI): Generate JS function proto for each of contract function
  es/contract/aci.js
  test/integration/contract.js
Labels: enhancement

#441 feat(Compiler/ACI): Make ACI compatible with compiler 3.0.0
  .env
  es/contract/aci.js
  es/contract/compiler.js
  es/contract/index.js
  test/integration/contract.js
Labels: enhancement
