Repository aeternity/aepp-sdk-js, pull requests merged in 2019-06, with the labels that each got.

#461 Release 3.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement

#457 feat(ACi): Make compatible with compiler 3.1.0
  .env
  es/ae/contract.js
  es/contract/aci.js
  es/contract/compiler.js
  test/integration/contract.js
Labels: feature, in progress

#472 feat(TX_BUILDER): Fix bug related to contract fee calculation.
  es/tx/builder/index.js
  es/tx/builder/schema.js
Labels: enhancement

#474 refactor(SCM): Update compatibility range for node: 3.0.1 - 4
  es/contract/compiler.js
  es/node.js
Labels: enhancement

#480 README: fix flavor link
  README.md
Labels: docs

#482 fix(RPC): Add contract contractDecodeCallResultAPI to RPC
  es/contract/index.js
Labels: enhancement

#479 fix(Compiler): Fix compiler compatibility mechanism
  es/contract/compiler.js
  test/integration/contract.js
Labels: bug

#485 build(webpack): Add another bundle for using in `<script>` tag
  docs/README.md
  docs/guides/import-script-tag.md
  es/node.js
  webpack.config.js
Labels: enhancement

#486 feat(Utils): Move json-bigint implementation to `utils`
  es/utils/http.js
  es/utils/json-big.js
  es/utils/swagger.js
  package-lock.json
  package.json
Labels: enhancement

#503 fix(Node): Do not throw error if `internalUrl` not provided
  es/node.js
Labels: enhancement

#498 fix(TXBuilder): Fix payload serialization if you try to pack unpack tx
  es/tx/builder/index.js
Labels: enhancement

#496 fix(TxValidator): Fix validation of state channel open transaction
  es/tx/validator.js
  test/integration/txVerification.js
Labels: bug

#505 feat(ACI): Refactor ACI module
  es/account/index.js
  es/account/selector.js
  es/accounts.js
  es/ae/aepp.js
  es/ae/contract.js
  es/ae/index.js
  es/ae/universal.js
  es/ae/wallet.js
  es/contract/aci.js
  es/contract/aci/helpers.js
  es/contract/aci/index.js
  es/contract/aci/transformation.js
  es/index.js
  examples/browser/vuejs/connect-two-ae/aepp/src/components/Home.vue
  examples/browser/vuejs/connect-two-ae/identity/src/components/Home.vue
  test/integration/contract.js
  test/integration/index.js
Labels: enhancement

#506 Release 4.1.0
  CHANGELOG.md
  README.md
  docker/sdk.env
  docs/api/account.md
  docs/api/ae/universal.md
  docs/api/ae/wallet.md
  docs/api/contract/aci.md
  docs/guides/import-script-tag.md
  es/account/index.js
  es/account/selector.js
  es/accounts.js
  es/ae/aepp.js
  es/ae/contract.js
  es/ae/index.js
  es/ae/universal.js
  es/ae/wallet.js
  es/contract/aci.js
  es/contract/aci/helpers.js
  es/contract/aci/index.js
  es/contract/aci/transformation.js
  es/index.js
  es/node.js
  es/tx/builder/index.js
  es/tx/validator.js
  examples/README.md
  examples/browser/vuejs/connect-two-ae/aepp/package.json
  examples/browser/vuejs/connect-two-ae/aepp/src/components/Home.vue
  examples/browser/vuejs/connect-two-ae/identity/package.json
  examples/browser/vuejs/connect-two-ae/identity/src/components/Home.vue
  package-lock.json
  package.json
  test/integration/channel.js
  test/integration/contract.js
  test/integration/index.js
  test/integration/txVerification.js
Labels: enhancement

#508 Realign 4.1.0
  CHANGELOG.md
  docker/sdk.env
  docs/api/account.md
  docs/api/ae/universal.md
  docs/api/ae/wallet.md
  docs/api/contract/aci.md
  examples/browser/vuejs/connect-two-ae/aepp/package.json
  examples/browser/vuejs/connect-two-ae/identity/package.json
  package-lock.json
  package.json
  test/integration/channel.js
Labels: enhancement
