Repository aeternity/aepp-sdk-js, pull requests merged in 2019-04, with the labels that each got.

#275 Improve channel rpc usage
  es/channel/handlers.js
  es/channel/index.js
  es/channel/internal.js
Labels: backlog, enhancement

#276 Improve channel tests and error handling
  es/channel/handlers.js
  test/integration/channel.js
Labels: backlog, enhancement

#300 Improve state channel params handling. Fixes #299
  es/channel/internal.js
Labels: review

#303 Compiler improvements
  docs/api/chain.md
  docs/api/contract/aci.md
  es/chain/index.js
  es/chain/node.js
  es/contract/compiler.js
  es/utils/crypto.js
  es/utils/http.js
  test/integration/accounts.js
Labels: review

#279 Channel contracts
  es/channel/handlers.js
  es/channel/index.js
  es/tx/builder/index.js
  es/tx/builder/schema.js
  es/utils/crypto.js
  test/integration/channel.js
Labels: backlog, feature

#305 Release 2.4.0
  .env
  CHANGELOG.md
  README.md
  docs/api.md
  docs/api/ae/contract.md
  docs/api/chain.md
  docs/api/contract.md
  docs/api/contract/aci.md
  docs/api/contract/compiler.md
  docs/api/contract/node.md
  docs/api/tx.md
  docs/api/utils/crypto.md
  docs/api/utils/keystore.md
  es/account/index.js
  es/ae/aens.js
  es/ae/contract.js
  es/chain/index.js
  es/chain/node.js
  es/channel/handlers.js
  es/channel/index.js
  es/channel/internal.js
  es/contract/aci.js
  es/contract/compiler.js
  es/contract/index.js
  es/contract/node.js
  es/index.js
  es/tx/builder/index.js
  es/tx/builder/schema.js
  es/utils/crypto.js
  es/utils/http.js
  es/utils/keystore.js
  es/utils/swagger.js
  examples/connect-two-ae/aepp/src/components/Home.vue
  package.json
  test/integration/accounts.js
  test/integration/channel.js
  test/integration/contract.js
  test/integration/index.js
  test/integration/transaction.js
Labels: review

#306 Realign/2.4.0
  CHANGELOG.md
  docs/api/account.md
  docs/api/ae/contract.md
  docs/api/contract/aci.md
  docs/api/utils/crypto.md
  es/account/index.js
  es/ae/aens.js
  es/ae/contract.js
  es/chain/index.js
  es/chain/node.js
  es/contract/aci.js
  es/utils/crypto.js
  es/utils/http.js
  examples/connect-two-ae/aepp/src/components/Home.vue
  package.json
  test/integration/contract.js
Labels: review

#309 Fix/rename contract methods in docs
  docs/api/ae/contract.md
  docs/api/channel/index.md
  docs/api/utils/crypto.md
  es/ae/contract.js
Labels: enhancement, review

#316 Get contract state support
  es/channel/index.js
  test/integration/channel.js
Labels: review

#315 State channels call contract static support
  es/channel/index.js
  test/integration/channel.js
Labels: review

#307 Get full channel state support
  es/channel/handlers.js
  es/channel/index.js
  test/integration/channel.js
Labels: review

#321 Adjust docs
  docs/api/ae/contract.md
  docs/api/contract/aci.md
  docs/usage.md
  es/account/index.js
  es/ae/contract.js
  es/contract/aci.js
Labels: review

#323 Release 2.4.1
  CHANGELOG.md
  docs/api/ae/contract.md
  docs/api/channel/index.md
  docs/api/contract/aci.md
  docs/api/utils/crypto.md
  docs/usage.md
  es/account/index.js
  es/account/memory.js
  es/ae/aepp.js
  es/ae/contract.js
  es/channel/handlers.js
  es/channel/index.js
  es/contract/aci.js
  es/contract/index.js
  es/utils/crypto.js
  es/utils/http.js
  examples/connect-two-ae/aepp/src/components/Home.vue
  examples/connect-two-ae/identity/src/components/Home.vue
  package.json
  test/integration/channel.js
  test/integration/index.js
Labels: in-progress

#327 Realign 2.4.1
  CHANGELOG.md
  docs/api/channel/index.md
  docs/usage.md
  es/utils/http.js
  package.json
Labels: review

#335 fix(ACI): Fix address type transformation when decoding data
  es/contract/aci.js
Labels: review

#331 feat(ACI): Update due to compiler API changes
  .env
  docker-compose.yml
  docker/sdk.env
  es/contract/aci.js
  test/integration/index.js
Labels: enhancement, review

#333 Feature/add contract to tx validator
  docs/api/contract/aci.md
  es/contract/aci.js
  es/tx/builder/schema.js
  es/tx/tx.js
  es/tx/validator.js
  test/integration/txVerification.js
Labels: in-progress, review

#284 Channel tx serializations
  es/channel/handlers.js
  es/channel/index.js
  es/channel/internal.js
  es/tx/builder/helpers.js
  es/tx/builder/index.js
  es/tx/builder/schema.js
  es/tx/tx.js
  es/utils/mptree.js
  test/integration/channel.js
  test/unit/mptree.js
Labels: in-progress, review

#338 feat(State Channels): Add cleanContractCalls method
  .env
  es/channel/handlers.js
  es/channel/index.js
  es/channel/internal.js
  test/integration/channel.js
Labels: review

#344 Release 3.0.0
  .env
  CHANGELOG.md
  docker-compose.yml
  docker/sdk.env
  docs/api/channel/index.md
  docs/api/contract/aci.md
  docs/api/tx/builder.md
  es/channel/handlers.js
  es/channel/index.js
  es/channel/internal.js
  es/contract/aci.js
  es/tx/builder/helpers.js
  es/tx/builder/index.js
  es/tx/builder/schema.js
  es/tx/tx.js
  es/tx/validator.js
  es/utils/mptree.js
  package-lock.json
  package.json
  test/integration/channel.js
  test/integration/index.js
  test/integration/txVerification.js
  test/unit/mptree.js
Labels: review

#345 Realign 3.0.0
  CHANGELOG.md
  docs/api/channel/index.md
  docs/api/tx/builder.md
  package-lock.json
  package.json
Labels: review

#346 test(State Channels): Fix channel tests to be compatible with aeterni…
  .env
  test/integration/channel.js
Labels: review

#349 feat(ACI): Add `contract`, `address`, `record` types argument/result transformation
  es/contract/aci.js
  test/integration/contract.js
Labels: review

#354 feat(Compiler): Add decode CallData by source/bytecode
  es/contract/compiler.js
  es/contract/index.js
Labels: review

#359 feat(RPC): Add getNodeInfo and getNetworkId to AEPP stamp through RPC
  es/account/index.js
  es/chain/index.js
  es/node.js
  es/rpc/client.js
Labels: feature

#324 feat(State Channels): Ping every 10 seconds to persist connection
  es/channel/handlers.js
  es/channel/index.js
  es/channel/internal.js
  test/integration/channel.js
Labels: review

#361 Release/3.1.0
  .env
  CHANGELOG.md
  docs/api/account.md
  docs/api/chain.md
  docs/api/channel/index.md
  docs/api/contract.md
  docs/api/tx/builder/schema.md
  es/account/index.js
  es/chain/index.js
  es/chain/node.js
  es/channel/handlers.js
  es/channel/index.js
  es/channel/internal.js
  es/contract/aci.js
  es/contract/compiler.js
  es/contract/index.js
  es/node.js
  es/rpc/client.js
  package-lock.json
  package.json
  test/integration/channel.js
  test/integration/contract.js
Labels: in progress
