Repository aeternity/aepp-sdk-js, pull requests merged in 2020-02, with the labels that each got.

#893 Feat(ACI): Implement Contract Events
  docs/guides/contract-events.md
  es/chain/node.js
  es/contract/aci/helpers.js
  es/contract/aci/index.js
  es/contract/aci/transformation.js
  package-lock.json
  test/integration/contract.js
Labels: feature

#895 Feat(Contract): helper for Oracle and AENS signature delegation
  docs/README.md
  docs/api.md
  docs/api/account.md
  docs/api/accounts.md
  docs/api/ae.md
  docs/api/ae/aens.md
  docs/api/ae/contract.md
  docs/api/ae/oracle.md
  docs/api/chain.md
  docs/api/chain/node.md
  docs/api/contract.md
  docs/api/contract/ga.md
  docs/api/tx.md
  docs/api/tx/builder/helpers.md
  docs/api/tx/tx.md
  docs/api/utils/aepp-wallet-communication/connection.md
  docs/api/utils/aepp-wallet-communication/rpc/rpc-client.md
  docs/guides/delegate-signature-to-contract.md
  es/ae/contract.js
  es/ae/oracle.js
  es/contract/aci/helpers.js
  es/contract/aci/transformation.js
  es/utils/string.js
  test/integration/aens.js
  test/integration/contract.js
Labels: feature

#897 feat(TxBuilder): Integrate amount formatter to transaction builder
  es/ae/index.js
  es/tx/builder/index.js
  es/tx/builder/schema.js
  es/utils/amount-formatter.js
  es/utils/bignumber.js
  test/integration/accounts.js
  test/integration/transaction.js
  test/unit/amount-formatter.js
Labels: feature

#903 Feat(Signing): Message Signing
  docs/api.md
  docs/api/account.md
  docs/api/contract/aci.md
  docs/api/utils/aepp-wallet-communication/rpc/aepp-rpc.md
  docs/api/utils/aepp-wallet-communication/rpc/wallet-rpc.md
  es/account/index.js
  es/utils/aepp-wallet-communication/rpc/aepp-rpc.js
  es/utils/aepp-wallet-communication/rpc/rpc-clients.js
  es/utils/aepp-wallet-communication/rpc/wallet-rpc.js
  es/utils/aepp-wallet-communication/schema.js
  es/utils/amount-formatter.js
  es/utils/crypto.js
  examples/browser/vuejs/connect-two-ae/identity/package-lock.json
  examples/browser/vuejs/connect-two-ae/identity/package.json
  examples/browser/vuejs/connect-two-ae/identity/src/components/Home.vue
  test/integration/contract.js
  test/integration/rpc.js
  test/unit/crypto.js
  test/unit/memory-account.js
Labels: feature

#911 feat(AEX-2): Use `hex` string for `signMessage` response
  es/account/index.js
  es/account/memory.js
  es/utils/aepp-wallet-communication/rpc/wallet-rpc.js
  test/integration/rpc.js
  test/unit/memory-account.js
Labels: enhancement

#910 refactor(Node): Move `getNetworkId` to helpers
  docs/api/node.md
  es/account/index.js
  es/node-pool/index.js
  es/node.js
Labels: enhancement

#912 Feat/Remove-aepp-rpc-client-from-wallet
  es/utils/aepp-wallet-communication/rpc/rpc-clients.js
  es/utils/aepp-wallet-communication/rpc/wallet-rpc.js
  test/integration/rpc.js
Labels: enhancement

#915 General fixes of example aepps
  examples/browser/vuejs/connect-two-ae/aepp/webpack.config.js
  examples/browser/vuejs/connect-two-ae/identity/src/components/Home.vue
  examples/browser/vuejs/connect-two-ae/identity/webpack.config.js
Labels: enhancement

#926 fix(AEX-2): Broken wallet detection
  es/utils/aepp-wallet-communication/connection/browser-window-message.js
  es/utils/aepp-wallet-communication/content-script-bridge.js
  es/utils/aepp-wallet-communication/wallet-detector.js
  examples/browser/extension/src/js/background.js
Labels: bug
