Repository aeternity/aepp-sdk-js, pull requests merged in 2022-01, with the labels that each got.

#1345 feat(error): introduce error types
  README.md
  docs/guides/error-handling.md
  src/account/memory.js
  src/account/multiple.js
  src/ae/aens.js
  src/ae/index.js
  src/ae/oracle.js
  src/chain/node.js
  src/channel/handlers.js
  src/channel/internal.js
  src/contract/aci/index.js
  src/contract/aci/transformation.js
  src/contract/compiler.js
  src/contract/ga/helpers.js
  src/contract/ga/index.js
  src/index.js
  src/node-pool/index.js
  src/node.js
  src/tx/builder/helpers.js
  src/tx/builder/index.js
  src/tx/tx-object.js
  src/tx/tx.js
  src/tx/validator.js
  src/utils/aepp-wallet-communication/connection/browser-runtime.js
  src/utils/aepp-wallet-communication/connection/browser-window-message.js
  src/utils/aepp-wallet-communication/content-script-bridge.js
  src/utils/aepp-wallet-communication/helpers.js
  src/utils/aepp-wallet-communication/rpc/aepp-rpc.js
  src/utils/aepp-wallet-communication/rpc/rpc-client.js
  src/utils/aepp-wallet-communication/rpc/wallet-rpc.js
  src/utils/aepp-wallet-communication/wallet-detector.js
  src/utils/amount-formatter.ts
  src/utils/bytes.ts
  src/utils/crypto.js
  src/utils/errors.ts
  src/utils/hd-wallet.js
  src/utils/keystore.js
  src/utils/mptree.ts
  src/utils/swagger.js
  test/integration/accounts.js
  test/integration/aens.js
  test/integration/channel.js
  test/integration/contract-aci.js
  test/integration/contract.js
  test/integration/node.js
  test/integration/rpc.js
  test/integration/txVerification.js
  test/unit/amount-formatter.ts
  test/unit/bytes.ts
  test/unit/hd-wallet.js
  test/unit/keystore.js
  test/unit/memory-account.js
  test/unit/mptree.ts
  test/unit/tx-object.js
  test/unit/tx.js
Labels: no breaking changes

#1375 feat(poll): use getCheckTxInPool if available
  src/chain/node.js
  src/node.js
  src/utils/errors.ts
  src/utils/swagger.js
  test/integration/node.js
Labels: minor breaking changes

#1363 Remove wrappers around compilerApi
  .github/workflows/main.yml
  docs/guides/connect-aepp-to-wallet.md
  docs/guides/error-handling.md
  examples/browser/aepp/src/Basic.vue
  examples/node/paying-for-tx-contract-call-tx.js
  package.json
  src/ae/aepp.js
  src/ae/contract.js
  src/contract/aci/index.js
  src/contract/compiler.js
  src/contract/ga/helpers.js
  src/contract/ga/index.js
  src/contract/index.js
  src/index.js
  src/utils/errors.ts
  test/integration/channel.js
  test/integration/contract-aci.js
  test/integration/contract.js
  test/integration/ga.js
  test/integration/transaction.js
Labels: minor breaking changes

#1395 chore: update @aeternity/aepp-calldata to 1.1.0
  package-lock.json
  package.json
  test/integration/contract-aci.js
Labels: review

#1374 fix(contract events): don't throw error if events emitted by remote
  test/integration/contract-aci.js
Labels: review

#1367 feat(aci): use dry-run to estimate gas and get rich errors
  docs/transaction-options.md
  src/ae/contract.js
  src/contract/aci.js
  src/contract/ga/index.js
  src/tx/builder/schema.js
  test/integration/contract-aci.js
  test/integration/contract.js
  test/integration/transaction.js
Labels: review

#1368 Remove deprecated contract methods
  docs/guides/contracts.md
  examples/node/contract-interaction.js
  src/ae/contract.js
  src/chain/index.js
  src/chain/node.js
  src/contract/aci.js
  src/contract/ga/index.js
  test/integration/aens.js
  test/integration/chain.js
  test/integration/contract-aci.js
  test/integration/contract.js
  test/unit/crypto.js
Labels: review, breaking changes
