Repository aeternity/aepp-sdk-js, pull requests merged in 2022-04, with the labels that each got.

#1058 index: Export in tree shaking friendly way
  docs/guides/aens.md
  docs/guides/build-wallet.md
  docs/guides/error-handling.md
  docs/quick-start.md
  examples/browser/wallet-iframe/src/App.vue
  examples/browser/wallet-web-extension/src/background.js
  examples/browser/wallet-web-extension/src/content-script.js
  examples/node/paying-for-tx-contract-call-tx.js
  examples/node/paying-for-tx-spend-tx.js
  src/ae/index.js
  src/ae/oracle.js
  src/index.js
  src/tx/builder/helpers.js
  src/tx/builder/index.js
  src/tx/builder/schema.js
  src/utils/amount-formatter.ts
  src/utils/bytes.ts
  src/utils/crypto.js
  src/utils/keystore.js
  test/integration/contract.js
  test/integration/index.js
  test/integration/paying-for.js
  test/unit/keystore.js
Labels: breaking changes

#1456 Generate compiler api in TypeScript using autorest
  .eslintrc.js
  .gitignore
  docs/guides/contracts.md
  package-lock.json
  package.json
  src/contract/aci.js
  src/contract/compiler.js
  src/utils/aepp-wallet-communication/rpc/aepp-rpc.js
  test/index.js
  test/integration/contract-aci.js
  test/integration/contract.js
  test/integration/index.js
  tooling/autorest/compiler.yaml
Labels: minor breaking changes

#1481 feat(utils): migrate hd-wallet.js to TS
  src/typings/bip32-path/index.d.ts
  src/typings/tweetnacl-auth/index.d.ts
  src/utils/crypto.ts
  src/utils/encoder.ts
  src/utils/hd-wallet.ts
  test/unit/hd-wallet.ts
Labels: refactoring

#1450 refactor(node)!: drop `internalUrl`
  docs/contrib/README.md
  docs/guides/low-vs-high-usage.md
  src/ae/contract.js
  src/chain/index.js
  src/chain/node.js
  src/node-pool/index.js
  src/node.js
  src/tx/tx.js
  src/utils/errors.ts
  src/utils/swagger.js
  test/integration/chain.js
  test/integration/channel.js
  test/integration/index.js
  test/integration/node.js
  test/integration/rpc.js
  test/integration/transaction.js
Labels: breaking changes

#1444 refactor(wallet rpc)!: don't pass networkId from aepp to wallet
  src/account/base.js
  src/account/rpc.js
  src/node.js
  src/utils/aepp-wallet-communication/rpc/aepp-rpc.js
  src/utils/aepp-wallet-communication/rpc/rpc-client.js
  src/utils/aepp-wallet-communication/rpc/wallet-rpc.js
  src/utils/aepp-wallet-communication/schema.ts
  test/integration/rpc.js
Labels: minor breaking changes

#1492 refactor(utils): migrate json-big.js to TS
  package-lock.json
  package.json
  src/utils/json-big.js
  src/utils/json-big.ts
  test/integration/channel.js
Labels: refactoring

#1490 refactor(utils): migrate keystore.js to ts
  docs/guides/error-handling.md
  package-lock.json
  package.json
  src/typings/@aeternity__argon2-browser/index.d.ts
  src/typings/@aeternity__uuid/index.d.ts
  src/utils/bytes.ts
  src/utils/crypto.ts
  src/utils/errors.ts
  src/utils/keystore.js
  src/utils/keystore.ts
  test/unit/keystore.ts
Labels: refactoring

#1494 refactor(chain)!: drop stamps and use plain functions
  docs/guides/connect-aepp-to-wallet.md
  examples/browser/aepp/src/Basic.vue
  src/ae/aens.js
  src/ae/aepp.js
  src/ae/index.js
  src/ae/universal.js
  src/ae/wallet.js
  src/chain.js
  src/chain/index.js
  src/chain/node.js
  src/contract/aci.js
  src/index.js
  src/tx/tx.js
  test/integration/accounts.js
  test/integration/channel.js
  test/integration/contract-aci.js
  test/integration/ga.js
  test/integration/paying-for.js
Labels: minor breaking changes
