Repository aeternity/aepp-sdk-js, pull requests merged in 2022-05, with the labels that each got.

#1505 refactor: migrate node-pool module to TS
  package-lock.json
  package.json
  src/node-pool/index.js
  src/node-pool/index.ts
  test/integration/node.ts
  tsconfig.json
Labels: refactoring

#1233 feat: generate node api in TypeScript
  .github/workflows/main.yml
  docker-compose.yml
  package-lock.json
  package.json
  src/chain.js
  src/chain.ts
  src/contract/compiler.js
  src/index.js
  src/node.js
  src/nodeApi.ts
  src/tx/validator.js
  src/utils/amount-formatter.ts
  src/utils/autorest.ts
  src/utils/swagger.js
  test/integration/aens.js
  test/integration/chain.js
  test/integration/channel.js
  test/unit/swagger.js
  tooling/autorest/compiler.yaml
  tooling/autorest/node.yaml
Labels: minor breaking changes

#1506 refactor(channel): migrate channel module to ts
  package-lock.json
  package.json
  src/channel/handlers.ts
  src/channel/index.js
  src/channel/index.ts
  src/channel/internal.js
  src/channel/internal.ts
  test/integration/channel.ts
Labels: refactoring

#1533 refactor(aepp-wallet)!: rewrite to ts all except rpc
  docs/guides/build-wallet.md
  docs/guides/connect-aepp-to-wallet.md
  docs/guides/error-handling.md
  examples/browser/aepp/src/Connect.vue
  examples/browser/wallet-iframe/src/App.vue
  examples/browser/wallet-web-extension/package.json
  examples/browser/wallet-web-extension/src/background.js
  examples/browser/wallet-web-extension/src/content-script.js
  package-lock.json
  package.json
  src/index.js
  src/utils/aepp-wallet-communication/connection-proxy.ts
  src/utils/aepp-wallet-communication/connection/Browser.ts
  src/utils/aepp-wallet-communication/connection/BrowserRuntime.ts
  src/utils/aepp-wallet-communication/connection/BrowserWindowMessage.ts
  src/utils/aepp-wallet-communication/connection/browser-runtime.js
  src/utils/aepp-wallet-communication/connection/browser-window-message.js
  src/utils/aepp-wallet-communication/connection/index.js
  src/utils/aepp-wallet-communication/content-script-bridge.js
  src/utils/aepp-wallet-communication/helpers.js
  src/utils/aepp-wallet-communication/rpc/aepp-rpc.js
  src/utils/aepp-wallet-communication/rpc/rpc-client.js
  src/utils/aepp-wallet-communication/rpc/wallet-rpc.js
  src/utils/aepp-wallet-communication/wallet-detector.js
  src/utils/aepp-wallet-communication/wallet-detector.ts
  src/utils/errors.ts
  test/integration/rpc.js
  tsconfig.json
Labels: breaking changes, refactoring
