Repository aeternity/aepp-sdk-js, pull requests merged in 2023-01, with the labels that each got.

#1708 feat(channel): add helper to get contract address created by other peer
  src/channel/Base.ts
  src/channel/Contract.ts
  src/channel/internal.ts
  test/integration/channel.ts
Labels: feature

#1711 refactor(channel): strongly type events
  src/channel/Base.ts
  src/channel/handlers.ts
  src/channel/internal.ts
Labels: refactoring

#1709 docs: add guide how to transfer fraction of funds
  examples/node/transfer-ae.mjs
  src/spend.ts
Labels: docs
